name: .NET App Build

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Find solution file
        id: find-sln
        run: |
          sln=$(find . -name "*.sln" | head -n 1)
          echo "Found solution: $sln"
          echo "sln_path=$sln" >> "$GITHUB_OUTPUT"

      - name: Restore dependencies
        run: dotnet restore ${{ steps.find-sln.outputs.sln_path }}

      - name: Build
        run: dotnet build ${{ steps.find-sln.outputs.sln_path }} --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ${{ steps.find-sln.outputs.sln_path }} --no-build --verbosity normal

      - name: Publish
        run: dotnet publish ./src/Project1/Project1.csproj -c Release -o ./publish
