name: Self-hosted Runner Test

on:
  push:

jobs:
  test-runner:
    runs-on: self-hosted  # or 'self-hosted' + 'ubuntu' if you use labels
    steps:
      - name: Print Runner Info
        run: |
          echo "Runner is working!"
          echo "Hostname: $(hostname)"
          echo "OS: $(uname -a)"
          echo "User: $(whoami)"
